[package]
name = "oldwebsite"
version = "0.1.0"
edition = "2018"
authors = ["Iván Molina Rebolledo"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
serde = "1.0.127"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.1"
features = ["handlebars", "tera"]